---
- name: Install and configure Grafana
  hosts: hostnode
  become: true
  tasks:
    - name: Install Grafana
      ansible.builtin.dnf:
        name: grafana
        state: present

    - name: Reload systemd daemon
      ansible.builtin.command:
        cmd: systemctl daemon-reload

    - name: Start and enable Grafana service
      ansible.builtin.systemd:
        name: grafana-server
        state: started
        enabled: true

    - name: Check Grafana service status
      ansible.builtin.command:
        cmd: systemctl status grafana-server
      register: grafana_status
      changed_when: false

