---
- name: Check and copy Foldclass CATH dataset to HDFS
  hosts: storagenode
  tasks:
  - name: Check CATH dataset existance in HDFS
    command: hdfs dfs -ls /data/almalinux/cath_foldclassdb/
    register: hdfs_check
    failed_when: hdfs_check.rc != 0 and "No such file or directory" not in hdfs_check.stderr
    changed_when: false

  - name: Copy CATH dataset to HDFS
    command: hdfs dfs -copyFromLocal /data/almalinux/cath_foldclassdb/ /cath_foldclassdb
    when: hdfs_check.rc != 0
