---
- name: Check and copy AlphaFold E.coli dataset to HDFS
  hosts: storagenode
  tasks:
  - name: Check E.coli dataset existance in HDFS
    command: hdfs dfs -ls /UP000000625_83333_ECOLI_v4
    register: hdfs_check
    failed_when: hdfs_check.rc != 0 and "No such file or directory" not in hdfs_check.stderr
    changed_when: false

  - name: Copy E.coli dataset to HDFS
    command: hdfs dfs -copyFromLocal /data/almalinux/UP000000625_83333_ECOLI_v4/ /UP000000625_83333_ECOLI_v4
    when: hdfs_check.rc != 0

